### ISSUE TITLE
Adding -prefer option to unison 

### ISSUE THREAD

**Issue by darron1217** [mickaelperrin/docker-magic-sync#12]
unison keep creates .tmp file which has conflict. Also it skips copying when file conflicted.

How about adding prefer option to this image?

BTW, thanks for this great image :)

**Comment by mickaelperrin** [comment]
Hi @darron1217,

You can override and customize the unison defaults ` -copyonconflict -auto -numericids -batch -maxerrors 10 -repeat watch` by using the environment variable `SYNC_UNISON_DEFAULTS`.

Hope it helps !
