### ISSUE TITLE
Files modifications is not reflected inside container

### ISSUE THREAD

**Issue by kconde2** [mickaelperrin/docker-magic-sync#13]

**Comment by mickaelperrin** [comment]
I still use this project everyday in my workflow and didn't notice very rare synchronisation problems. That may still occurs when you run heavy synchronisation tasks as explained in the README.

You only have to restart the container to relaunch the synchronisation process.

If nothing is working, it should be a configuration problem. Be sure you use the same volume for your application container and for the magic-sync container.

**Comment by kconde2** [comment]
Maybe, this is due to my MacOS configuration but now I'm using NFS volumes for sharing files.

https://vivait.co.uk/labs/docker-for-mac-performance-using-nfs

Thanks for your answer.
