### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by lukasvtechceo** [mickaelperrin/docker-magic-sync#6]
While starting a container I get an error:

magic-sync_1             | usermod: no changes
magic-sync_1             | Traceback (most recent call last):
magic-sync_1             |   File "/config_sync.py", line 167, in <module>
magic-sync_1             |     c.set(sys.argv[1])
magic-sync_1             |   File "/config_sync.py", line 164, in set
magic-sync_1             |     self.initial_sync()
magic-sync_1             |   File "/config_sync.py", line 155, in initial_sync
magic-sync_1             |     os.sytem('unison ' + volume + '.magic ' + volume + ' -auto -batch ' + self.generate_ignore_string(conf['ignore'], 'unison'))
magic-sync_1             | AttributeError: 'module' object has no attribute 'sytem'

**Comment by mickaelperrin** [comment]
Sorry for the typo, fixed by #5
